### ISSUE TITLE
Can't use TinyNetworking with Carthage

### ISSUE THREAD

**Issue by bonkowski** [objcio/tiny-networking#13]
Added github "https://github.com/objcio/tiny-networking" to my Cartfile
Run carthage update --platform iOS

Dependency "tiny-networking" has no shared framework schemes for any of the platforms: iOS
 Xcode 10.2.1

**Comment by chriseidhof** [comment]
I don’t know much about Carthage, currently we only support SwiftPM

**Comment by bonkowski** [comment]
I understand. It seems that Carthage depends on shared schemes. I have not been able to use SPM, (waiting for a proprietary library to support Swift 5.1), so I don't know how schemes are handled in SPM. 

https://github.com/Carthage/Carthage#share-your-xcode-schemes

**Comment by bonkowski** [comment]
We have now got Swift 5.1 support for the proprietary library we are using, and moved to use SPM. I'll just want to say that TinyNetworking is working great. I'll love it! ❤️
