### ISSUE TITLE
Please tag latest release 

### ISSUE THREAD

**Issue by jagreenwood** [objcio/tiny-networking#22]
I've got two packages which are dependent on this package and SwiftPM is unable to reconcile. 

I believe tagging the latest commit on `master` will resolve my issue.

**Comment by chriseidhof** [comment]
Sure thing. I just tagged `master` as 0.4.1. Let me know if that helps.

**Comment by jagreenwood** [comment]
@chriseidhof yup that resolves it. Thank you!
