### ISSUE TITLE
Cannot build with Xcode 12.5.1 or earlier

### ISSUE THREAD

**Issue by davidjrogers** [objcio/tiny-networking#26]
This code does not build with Xcode 12.5.1. Only works with not yet publicly released versions of iOS and dev tools.

The changes from https://github.com/objcio/tiny-networking/pull/25 require beta iOS 15 developer tools and may not be backward compatible. Of course this hinges on what Apple releases next week but I feel that merging changes like this that are currently in beta are premature.

Building on Big Sur with Xcode 12.5.1 results in an error `'async' modifier is only valid when experimental concurrency is enabled` on line 289 of Endpoint.swift.

**Comment by chriseidhof** [comment]
Oh that's definitely something we should fix! If you have time please send a PR, otherwise I can look into this sometime next week.

**Comment by davidjrogers** [comment]
Unfortunately I'm not sure right now how to fix it. Maybe something like wrapping the function in 

`#if swift(>=5.5)` ?

**Comment by chriseidhof** [comment]
Hey @davidjrogers, I think this should be fixed now!
