### ISSUE TITLE
Cannot Archive with TinyNetworking as Swift Package in Xcode 13 RC

### ISSUE THREAD

**Issue by Danny-SS** [objcio/tiny-networking#27]
In my main project we have been waiting for Xcode 13 RC to drop to hopefully fix the errors when trying to archive a project that has TinyNetworking.  It has always compiled, built and archived with Xcode 12.5.x and we have been using this package for our new features.

Xcode 13 RC was released a few hours ago.

However, we are still getting errors when archiving (building and running from Xcode 13 RC work fine still).

To replicate, I created a brand new Xcode project in Xcode 13RC.  It was a SwiftUI app.  I did no coding and immediately archived. It was successfully archived.  Then I added TinyNetworking through the SPM Xcode interface.  I could build and run and saw "Hello World" on my physical device.  Lastly, I tried to archive the project and there was the error again.

"Cannot find 'dataTaskPublisher' in scope"

![Screen Shot 2021-09-14 at 6 28 04 PM](https://user-images.githubusercontent.com/31970539/133342144-1a96e009-f284-47cb-b30f-1cd26814f377.png)

**Comment by Danny-SS** [comment]
![Screen Shot 2021-09-14 at 6 33 14 PM](https://user-images.githubusercontent.com/31970539/133342609-a2df7527-31c7-483b-8a56-c7f4fa465761.png)

**Comment by Danny-SS** [comment]
Finally here is the Archive log.

CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler (in target 'TinyNetworking' from project 'TinyNetworking')
    cd /Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/SourcePackages/checkouts/tiny-networking
    export DEVELOPER_DIR\=/Applications/Xcode\ 13.app/Contents/Developer
    export SDKROOT\=/Applications/Xcode\ 13.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk
    /Applications/Xcode\ 13.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc -incremental -module-name TinyNetworking -O -whole-module-optimization -enforce-exclusivity\=checked @/Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/IntermediateBuildFilesPath/TinyNetworking.build/Release-iphoneos/TinyNetworking.build/Objects-normal/arm64/TinyNetworking.SwiftFileList -DSWIFT_PACKAGE -DXcode -sdk /Applications/Xcode\ 13.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk -target arm64-apple-ios9.0 -g -module-cache-path /Users/ssdev/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -Xfrontend -serialize-debugging-options -embed-bitcode -swift-version 5 -I /Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/BuildProductsPath/Release-iphoneos -I /Applications/Xcode\ 13.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/lib -F /Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/BuildProductsPath/Release-iphoneos -F /Applications/Xcode\ 13.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks -F /Applications/Xcode\ 13.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/Developer/Library/Frameworks -parse-as-library -c -num-threads 12 -output-file-map /Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/IntermediateBuildFilesPath/TinyNetworking.build/Release-iphoneos/TinyNetworking.build/Objects-normal/arm64/TinyNetworking-OutputFileMap.json -parseable-output -serialize-diagnostics -emit-dependencies -emit-module -emit-module-path /Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/IntermediateBuildFilesPath/TinyNetworking.build/Release-iphoneos/TinyNetworking.build/Objects-normal/arm64/TinyNetworking.swiftmodule -Xcc -I/Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/IntermediateBuildFilesPath/TinyNetworking.build/Release-iphoneos/TinyNetworking.build/swift-overrides.hmap -Xcc -I/Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/BuildProductsPath/Release-iphoneos/include -Xcc -I/Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/IntermediateBuildFilesPath/TinyNetworking.build/Release-iphoneos/TinyNetworking.build/DerivedSources-normal/arm64 -Xcc -I/Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/IntermediateBuildFilesPath/TinyNetworking.build/Release-iphoneos/TinyNetworking.build/DerivedSources/arm64 -Xcc -I/Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/IntermediateBuildFilesPath/TinyNetworking.build/Release-iphoneos/TinyNetworking.build/DerivedSources -Xcc -DSWIFT_PACKAGE -emit-objc-header -emit-objc-header-path /Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/Build/Intermediates.noindex/ArchiveIntermediates/TestTiny/IntermediateBuildFilesPath/TinyNetworking.build/Release-iphoneos/TinyNetworking.build/Objects-normal/arm64/TinyNetworking-Swift.h -working-directory /Users/ssdev/Library/Developer/Xcode/DerivedData/TestTiny-bxtbxjycmspnzdejroqyjlpxjmsi/SourcePackages/checkouts/tiny-networking

remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
Command CompileSwiftSources failed with a nonzero exit codeiphoneos -F /Applications/Xcode\

**Comment by chriseidhof** [comment]
Hi @Danny-SS! That's a bit unfortunate... do you have an idea what might be causing this? 

I imagine this is when exporting an iOS app, right? For a Mac app it seems to work.

**Comment by Danny-SS** [comment]
@chriseidhof I am not 100% sure what is causing this. This is for an iOS project.   

Yes.  This is when I am trying to archive my project before I upload it to Apple.  

Update:

When I took the Endpoint.swift out of the package, added it directly as source to project and removed TinyNetworking Package, I could build and archive like normal.  So this seems to be something on how the Package is defined possibly.

In the last Xcode 13 Beta, beta 8, we were seeing issues complaining about Combine and Swift 5.5.  I know some other third-party dependencies were having a very similar problem.

I'll continue to research and test in my example.  #canImport seems to be area I will investigate

**Comment by Danny-SS** [comment]
**Update**
Here is a relevant discussion from the Apple Dev Forums.

[https://developer.apple.com/forums/thread/682285](url)

Mid-way down in the thread , it seems like  .platforms: [ .iOS(.v12), .macOS(.v10_14), .tvOS(.v12), .watchOS(.v5) ] in the Package resolved this for some. (I had to expand a thread)

TinyNetworking has no .platforms defined in the Package file, so I am wondering if this the issue.

This is just my best hunch while I continue to experiment with this.

**Comment by Danny-SS** [comment]
FYI, I created a Mac app in Xcode 13 RC.  Ran, saw "Hello World".  I was able to archive, no problem.  I added TinyNetworking to project.  I could still build and run.  However, going to Product > Archive, failed just like in iOS.  @chriseidhof I know you said for a Mac app, it worked fine for you.

Am I missing something?

**Comment by boyceEstes** [comment]
I had the same issue to archive my project in Xcode 13 RC. I was able to solve it by copy/pasting the Endpoint.swift file into my main iOS project and removing the tiny networking package dependency.

**Comment by Danny-SS** [comment]
Thanks @boyceEstes,  at least you could reproduce the issue.  I had the same success with just copying the Endpoint.swift file into the main project.  It certainly defeats the promise of Swift Packages - but at least we can archive and get our iOS 15 RC changes to TestFlight.

I'll keep researching if there are ways use this package again as I move forward.

**Comment by Danny-SS** [comment]
@chriseidhof ... while ingesting the Endpoint.swift file directly into my iOS project worked to archive and sent up to the Apple App Store, I am not satisfied with this solution long term.

In investigating what other Package contributors did to get around this issue (and explain it better) had to do with replacing the conditional complication directive of

`#if canImport(Combine)`

with 

`#if !(os(iOS) && (arch(i386) || arch(arm)))`

https://github.com/realm/realm-cocoa/pull/7401   (Pull Request Details)

https://github.com/realm/realm-cocoa/pull/7401/files (changes)

This is a work-around for a Xcode 13's broken swiftfinterface file for Combine on 32-bit iOS.  

(I did indeed trying changing the directive and for the first time I could archive).  I have not done any further testing yet.  I just wanted to see if you had any thoughts.

**Comment by chriseidhof** [comment]
I think this should not be an issue anymore, right? I'll close it (to clean up the issue list), let me know if it needs reopening.
