### ISSUE TITLE
Cannot compile with Xcode 13

### ISSUE THREAD

**Issue by davidjrogers** [objcio/tiny-networking#28]
Line 292 of Endpoint.swift.

Use of local variable 'data' before its declaration

**Comment by chriseidhof** [comment]
Hey @davidjrogers, sorry about that, I'm not sure why Xcode doesn't like that. It's the async/await stuff, but I thought it was properly behind conditional compilation.

In any case, you should be able to work around this by depending on a specific tag instead of master. Please reopen if that doesn't fix this issue.

**Comment by davidjrogers** [comment]
Shouldn't it get fixed in master too? The fact that it doesn't compile where it should be supported doesn't sound like the issue is resolved.

**Comment by chriseidhof** [comment]
Yes, you're right. I think I'll just reopen it and hope that this'll get fix in the next version of Xcode. I don't have the time to dig into the underlying cause right now, but am very happy to take a PR.

**Comment by jagreenwood** [comment]
Might be related... Xcode 13 broke archiving (and building with `Any iOS Device` build target) for me with the error `Cannot find 'dataTaskPublisher' in scope`. 

I added the following to my package and it works again:

```swift
platforms: [
    .iOS(.v13),
    .macOS(.v10_15)
],
```

So it kind of seems like `@available` is not working correctly in packages.

@davidjrogers you might try forking and setting the platform to `v15` and see if that helps.

**Comment by chriseidhof** [comment]
I think this should be fixed in the latest commit... let me know if this is still an issue and I'll reopen it =)
