### ISSUE TITLE
Allow other http loading infrastructure

### ISSUE THREAD

**Issue by tomquist** [objcio/tiny-networking#5]
Since `expectedStatusCode` and `parse` are both internal it's not possible to reimplement the `load` method using a different url request loading infrastructure, e.g. using Alamofire or some other http client. Is there a specific reason they're not public?

**Comment by chriseidhof** [comment]
Hi @tomquist, happy to make them public, open for PRs =).

Just out of curiosity: why would you want to use AlamoFire instead of URLSession directly? (I'm not very familiar with AF).

**Comment by tomquist** [comment]
Great to hear. Will create a PR soon.

Not sure about Alamofire, was just an example from the top of my head that made sense without bothering you with my specific use case which is a wrapper around `NSURLSession` that allows intercepting request loading for logging or transparently adding OAuth2 auth headers etc.

In a different test project I also wanted to add an extension to `NSURLSession` to load an endpoint that uses the `NSURLSession` extensions provided by `Combine` for loading an endpoint.

**Comment by chriseidhof** [comment]
With the current API, it should be possible to provide a wrapper around URLSession, and you can modify the request to add headers, I think. Let me know if you run into any trouble with that.

Doing a Combine based API also sounds very interesting!

**Comment by chriseidhof** [comment]
@tomquist I'm closing this because there's no concrete action I can take for now. Happy to look at a PR later on should you need more functionality. =)
